---
title: "ST2195 Programming for Data Science"
author: "Lee Hin Sing Raymond"
date: "January 2022"
output: pdf_document
---

# Practice Assignment 4

### Introduction

This is the fourth assignment for the course [**ST2195 Programming for Data Science**](https://www.lse.ac.uk/study-at-lse/uolip/Assets/documents/21-22-CIS-Sheets/ST2195-Programming-for-data-science.pdf). R and Python programming will be the main focus of this introductory course.

This is a compulsory 200-course for students who are going for a **BSc Data Science and Business Analytics** degree in the University of London, the academic direction of the degree program is provided by [London School of Economics and Political Science](https://www.lse.ac.uk/) (LSE). The course convenors are Mr [Ioannis Kosmidis](https://www.ikosmidis.com/) and Dr [Kostas Kalogeropoulos](https://www.lse.ac.uk/Statistics/People/Dr-Kostas-Kalogeropoulos).

Throughout the half-year course, there will be a take-home assignment every two weeks to demonstrate what we have learned before. All final works should be uploaded to a GitHub repository for version control.

### Assignment

Create a GitHub repository called “st2195_assignment_4”:

* Commit/push the code below as a file called "foo.R"

* Find and fix all the bugs in the code [1 point is awarded for every fixed bug]. 
Instructions are given in the form of comments in the code

* Update "foo.R" by committing and pushing the revisions.

```{r}
# foo.R
# Radius
r <- 2

# Function to compute the volume of a sphere with radius r
volume <- function(r, rho) {
  3/4*pi*r^2
}

# Function to compute the volumes of the spheres with radius r, r^2 and r^3
volume_vector <- function(r) {
  r <- 22
  for (r in 2:4) {
    volume(r)
  }
}

# Run volume_vector(r) and print the volumes of the spheres with radius r, r^2 and r^3
volume_vector(r)
```
